In [1]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualizaciones
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree



# Para realizar la regresión lineal y la evaluación del modelo
# -----------------------------------------------------------------------
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import r2_score, mean_absolute_error
import pickle
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from category_encoders import TargetEncoder



from sklearn.model_selection import KFold,LeaveOneOut, cross_val_score


from sklearn.preprocessing import StandardScaler

from tqdm import tqdm


# Ignorar los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings('ignore')


pd.options.display.float_format = "{:,.2f}".format 
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv('../datos/datos_cluster_kmeans.csv', index_col=0)
df.head(2)

df_cluster3 = df[df["clusters_kmeans"] == 1]
df_cluster3.head()

,Ship Mode,Segment,City,State,Country,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Order Priority,clusters_kmeans,Profit_respuesta
0,0.05,0.52,0.02,0.02,0.19,0.19,0.06,0.00,0.20,0.06,0.00,10.10,1.33,0.00,42.39,0.08,1,762.18
1,0.20,0.30,0.00,0.02,0.06,0.21,0.07,0.00,0.19,0.07,0.00,16.45,2.00,0.50,41.93,0.08,1,-288.76
2,0.15,0.52,0.00,0.01,0.06,0.21,0.07,0.00,0.20,0.07,0.00,23.11,2.00,0.50,41.56,0.57,1,919.97
3,0.15,0.18,0.00,0.00,0.04,0.19,0.22,0.00,0.20,0.07,0.00,12.74,0.67,0.50,41.32,0.57,1,-96.54
4,0.05,0.52,0.00,0.00,0.00,0.09,0.09,0.00,0.20,0.04,0.00,12.47,1.67,0.00,40.99,0.08,1,311.52

In [3]:
#separamos x e y para predecir nuestro modelo
x= df.drop(columns="Profit_respuesta")
y= df[["Profit_respuesta"]]

In [4]:
#Separamos train y test
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size= 0.7, random_state=42)

Modelo

In [5]:
# Si y es un DataFrame, conviértelo a Serie
if isinstance(y, pd.DataFrame):
    y = y.iloc[:, 0]  # Convertir a Serie

# Dividimos los datos en train y test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=42)

# Verificar las formas de X_train, X_test, y_train, y_test
print(f"Forma de X_train: {X_train.shape}")
print(f"Forma de X_test: {X_test.shape}")
print(f"Forma de y_train: {y_train.shape}")
print(f"Forma de y_test: {y_test.shape}")

# Entrenamos los datos
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Predecimos
y_pred = model.predict(X_test)

# Calculamos el RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# Calculamos el coeficiente R^2
r2 = r2_score(y_test, y_pred)

print("Precio real vs Predicción:")
display(pd.DataFrame({'Real': y_test.values, 'Predicción': y_pred}).head(2))  # Mostrar los primeros 2 resultados
print(f"\nRMSE: {rmse:.2f}")
print(f"R^2: {r2:.2f}")

Forma de X_train: (10258, 17)
Forma de X_test: (41032, 17)
Forma de y_train: (10258,)
Forma de y_test: (41032,)
Precio real vs Predicción:

   Real  Predicción
0 -1.27       -2.25
1  3.63        3.49

RMSE: 94.15
R^2: 0.72