In [10]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Visualizaciones
# -----------------------------------------------------------------------
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import tree



# Para realizar la regresión lineal y la evaluación del modelo
# -----------------------------------------------------------------------
from sklearn.tree import DecisionTreeRegressor, plot_tree
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import r2_score, mean_absolute_error
import pickle
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from category_encoders import TargetEncoder



from sklearn.model_selection import KFold,LeaveOneOut, cross_val_score


from sklearn.preprocessing import StandardScaler

from tqdm import tqdm


# Ignorar los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings('ignore')


pd.options.display.float_format = "{:,.2f}".format 
pd.set_option("display.max_columns", None)

In [11]:
df = pd.read_csv('../datos/datos_cluster_kmeans.csv', index_col=0)
df.head(2)

df = df[df["clusters_kmeans"] == 2]
df.head()

,Ship Mode,Segment,City,State,Country,Market,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Order Priority,clusters_kmeans,Profit_respuesta
9,0.20,0.52,0.00,0.00,0.19,0.19,0.13,0.00,0.19,0.02,0.00,19.12,3.33,2.00,39.28,0.08,2,"-1,862.31"
32,0.05,0.52,0.00,0.02,0.19,0.19,0.22,0.00,0.19,0.07,0.00,10.75,0.67,1.50,31.26,0.30,2,-350.49
37,0.05,0.30,0.00,0.00,0.19,0.19,0.13,0.00,0.20,0.03,0.00,35.93,0.33,2.50,30.54,0.30,2,"-3,839.99"
73,0.15,0.30,0.00,0.00,0.03,0.21,0.06,0.00,0.19,0.02,0.00,15.17,1.33,2.35,26.50,0.30,2,-452.81
83,0.20,0.52,0.01,0.01,0.19,0.19,0.06,0.00,0.19,0.07,0.00,19.66,2.00,1.50,25.59,0.57,2,-630.88

In [12]:
#separamos x e y para predecir nuestro modelo
x= df.drop(columns="Profit_respuesta")
y= df[["Profit_respuesta"]]

In [13]:
df = df.drop(columns=['Shipping Cost','Product ID','Product Name','clusters_kmeans','Sub-Category','Region','Segment','State'])

In [14]:
#Separamos train y test
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size= 0.7, random_state=42)

Modelo

In [15]:
# Si y es un DataFrame, conviértelo a Serie
if isinstance(y, pd.DataFrame):
    y = y.iloc[:, 0]  # Convertir a Serie

# Dividimos los datos en train y test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.8, random_state=42)

# Verificar las formas de X_train, X_test, y_train, y_test
print(f"Forma de X_train: {X_train.shape}")
print(f"Forma de X_test: {X_test.shape}")
print(f"Forma de y_train: {y_train.shape}")
print(f"Forma de y_test: {y_test.shape}")

# Entrenamos los datos
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Predecimos
y_pred = model.predict(X_test)

# Calculamos el RMSE
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# Calculamos el coeficiente R^2
r2 = r2_score(y_test, y_pred)

print("Precio real vs Predicción:")
display(pd.DataFrame({'Real': y_test.values, 'Predicción': y_pred}).head(2))  # Mostrar los primeros 2 resultados
print(f"\nRMSE: {rmse:.2f}")
print(f"R^2: {r2:.2f}")

Forma de X_train: (123, 17)
Forma de X_test: (496, 17)
Forma de y_train: (123,)
Forma de y_test: (496,)
Precio real vs Predicción:

     Real  Predicción
0 -776.33     -687.29
1 -535.44     -631.42

RMSE: 442.12
R^2: 0.14